MAPFILE = "teste.map"
CEMPADIR = "/STORAGE/catalog/cempa/"
N_POOL = 10
vars = ['albedt','tempc','ue_avg','ve_avg',
'w','rh','geo','cloud','precip','acccon',
'sfc_press','sea_press','t2mj','td2mj','u10mj',
'v10mj','le','h','rshort','rlong','rlongup']
DBLINK = 'sqlite:////data.bd'

IGNOREHASHFILE = true
forceCreateFiles = false
FORCE_SAVE_BD = false